@startuml
object "Persona" as Persona{
    Nombre: "1 Texto"
    Primer apellido: "1 Texto"
    Segundo apellido: "0..1 Texto"
    Fecha de nacimiento: "1 Tiempo"
    Sexo: "1 Texto"
    Número de identificación: "0..1 Texto"
}
@enduml