@startuml
object "Cuadro" as cuadro{

  Título: 0..* Texto Lugar
  Cronología: 1 Tiempo
  Técnica: 1 enum Técnica
  Sub-técnica: 1 enum Sub-Técnica
  Material del soporte: 1 enum Material
  Autor: 1 Texto
  Estado de conservación: 1 enum Estado de Conservación
}

object  Replica {
    Título: 0..* Texto
    Cronología: 1 Tiempo
    Técnica: 1 enum Técnica
    Sub-técnica: 1 enum Sub-Técnica
    Material del soporte: 1 enum Material
    Autor: 1 Texto
    Estado de conservación: 1 enum Estado de Conservación
}

object "Lugar" as l1{

    Institución: 1 Texto
    Ciudad: 1 Texto
    País: 1 Texto
}



 l1 "1" -- "0..*" cuadro : < Se localiza en

cuadro "1" -- "0..*" Replica: < Es replica de


@enduml