@startuml
class "Cuadro" as Cuadro {
    Título: "0..* Texto"
    Cronología: "1 Tiempo"
    Técnica: "1 enum Técnica"
    Sub-técnica: "1 enum Sub-Técnica"
    Material del soporte: "1 enum Material"
    Autor: "1 Texto"
    Estado de conservación: "1 enum Estado de Conservación"
}

enum Técnica{
    Acuarela
    Óleo
    Pastel
    Fresco
}

enum Sub-Técnica:{
Sfumato
Pincelada simple
Collage
Veladura
}

enum Material{
    Madera
    Álamo
    Nogal
    Lienzo
    Obra
}


enum "Estado de Conservación" as estaddeConservacion{
    Excelente
    Bueno
    Regular
    Malo
    Destruido
}

@enduml