@startuml
class "Actuacion" as Actuacion{
    Fecha de inicio: "1 Tiempo"
    Fecha de fin: "0..1 Tiempo"
    Tipo: "1 enum Tipo de Actuación"
}

enum "Tipo de Actuación" as TipoActuacion{
    Sondeo
    Excavación
    Seguimiento
}

@enduml