@startuml

object "Catedral De Santiago: Edificio" as CatedralDeSantiago{

    Nombre = “Catedral de Santiago de Compostela”
    Culto = "Católico"
    Lugar = “Santiago de Compostela, G alicia, España"
    Fecha inicio construcción = "1075"
    Fecha fin construcción = "112 2"
    Fecha primera consagración = "1128"
    Fecha inicio segunda etapa construcción = ""1168"
    Fecha segunda consagración = "3 de abril de 121 1"
    Fecha declaración BIC = "1896"
    Material = "Granito"
    Estilo = "Románico, Gótico, Bar roco, Platere sco, Neoclásico"

}

@enduml

